language: node_js
node_js:
  - "8"
branches:
  only:
  - /^release\/.+$/
script:
- npm run release-it
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: "dist"
  on:
    branch: master
